apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancherupgrade-stg
spec:
  destination:
    namespace: rancherupgrade-stg
    server: https://kubernetes.default.svc
  project: rancherupgrade
  source:
    chart: rancher-upgrade-tool
    helm:
      parameters:
        - name: ingress.host
          value: stg.rancher.tips
    repoURL: https://charts.support.tools
    targetRevision: CHARTVERSION
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: "30m"
        factor: 2
        maxDuration: "5m"
