apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: rancherupgradetool
    team: SupportTools
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: rancherupgradetool
    team: SupportTools